# Generated by Django 4.2.19 on 2025-03-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measuriment_unit',
            new_name='measurement_unit',
        ),
    ]
