# Generated by Django 4.2.19 on 2025-03-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_shortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
